name: Publish image to Docker Hub
on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

jobs: 
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t norristimmy/final_project:latest
      - name: publish
        run: |
          docker push norristimmy/final_project:latest
